import {Injectable} from "@angular/core";

@Injectable()
export class RequestResponseParser {
  user = {
    "data":{
      "id":"57",
      "type":"users",
      "attributes":{
        "first-name":"Mckayla",
        "description":"Semiotics keffiyeh bicycle rights. Try-hard tattooed waistcoat salvia pug deep v.",
        "job-experience":null,
        "education":null,
        "language-id":37,
        "zip":"11850",
        "zip-latitude":59.3164285,
        "zip-longitude":18.0590482,
        "competence-text":null,
        "primary-role":"company",
        "phone":"665-224-0775",
        "street":"Wollmar Yxkullsgatan 20",
        "latitude":null,
        "longitude":null,
        "email":"company@example.com",
        "last-name":"Rice",
        "created-at":"2016-04-07T18:45:49.429+02:00",
        "updated-at":"2016-05-08T13:06:31.548+02:00",
        "admin":false,
        "anonymized":false,
        "ignored-notifications":[

        ],
        "frilans-finans-payment-details":false,
        "ssn":"8791488414",
        "current-status":null,
        "at-und":null,
        "arrived-at":null,
        "country-of-origin":null,
        "auth-token":"eaa8602b1db03801e902e8dd48f2a240e8c43853bb46e932c900bb78a9d15da61ed5dfbb09b9fa276a54684a99d6e355da1dff13a33f7942c302c3a44539357c"
      },
      "relationships":{
        "company":{
          "data":{
            "id":"7",
            "type":"companies"
          },
          "links":{
            "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/7"
          }
        },
        "language":{
          "data":{
            "id":"37",
            "type":"languages"
          },
          "links":{
            "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
          }
        },
        "user-images":{
          "data":[

          ]
        },
        "languages":{
          "data":[

          ],
          "links":{
            "related":"https://just-match-api-staging.herokuapp.com/api/v1/users/57/languages"
          }
        },
        "chats":{
          "data":[
            {
              "id":"325",
              "type":"chats"
            },
            {
              "id":"329",
              "type":"chats"
            }
          ],
          "links":{
            "related":"https://just-match-api-staging.herokuapp.com/api/v1/users/57/chats"
          }
        }
      },
      "links":{
        "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/57"
      }
    },
    "included":[
      {
        "id":"7",
        "type":"companies",
        "attributes":{
          "name":"Bahringer LLC",
          "website":null,
          "cin":"5527820012",
          "street":"Sveavägen 1",
          "zip":"11850",
          "city":"stockholm",
          "phone":null,
          "email":"d3b285ae-17ee-4797-b9eb-61d1596f375a@example.com"
        },
        "relationships":{
          "company-images":{
            "data":[

            ]
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/7"
        }
      },
      {
        "id":"37",
        "type":"languages",
        "attributes":{
          "lang-code":"en",
          "direction":"ltr",
          "system-language":true,
          "local-name":"English",
          "en-name":"English",
          "sv-name":"Engelska",
          "ar-name":"الإنجليزية",
          "fa-name":"انگلیسی",
          "fa-af-name":"انگلیسی",
          "ku-name":"English",
          "ti-name":"እንግሊዝኛ",
          "ps-name":"انګلیسي"
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
        }
      }
    ]
  };
  jobs = {
    "data":[
      {
        "id":"256",
        "type":"jobs",
        "attributes":{
          "description":"This is the job description. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?",
          "job-date":"2016-07-26T00:00:00.000+02:00",
          "hours":2.0,
          "name":"Short Description",
          "created-at":"2016-07-25T15:08:09.430+02:00",
          "updated-at":"2016-07-25T15:08:09.430+02:00",
          "zip":"11157",
          "zip-latitude":59.3335278,
          "zip-longitude":18.0656418,
          "verified":false,
          "job-end-date":"2016-07-26T00:00:00.000+02:00",
          "filled":false,
          "short-description":"This is the job summary",
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"403",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/403"
            }
          },
          "company":{
            "data":{
              "id":"31",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/31"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "category":{
            "data":{
              "id":"12394",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/12394"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"9",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/9"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/256"
        }
      },
      {
        "id":"255",
        "type":"jobs",
        "attributes":{
          "description":"asdadasdasdasdaadasd",
          "job-date":"2016-07-23T00:00:00.000+02:00",
          "hours":8.0,
          "name":"asd",
          "created-at":"2016-07-25T15:05:31.493+02:00",
          "updated-at":"2016-07-25T15:05:31.493+02:00",
          "zip":"12345",
          "zip-latitude":59.2501695,
          "zip-longitude":18.0977249,
          "verified":false,
          "job-end-date":"2016-07-25T00:00:00.000+02:00",
          "filled":false,
          "short-description":"asdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdaasdasdadasdaasdasasdadasdsa",
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"403",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/403"
            }
          },
          "company":{
            "data":{
              "id":"31",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/31"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "category":{
            "data":{
              "id":"12393",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/12393"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"9",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/9"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/255"
        }
      },
      {
        "id":"254",
        "type":"jobs",
        "attributes":{
          "description":"Lorem ipsum dolor sit amet, soleat menandri usu an, has veniam aliquando cu. Atqui fierent an quo. Nec te dicit melius deterruisset, cum natum invenire consulatu an. Graeci suavitate pertinacia ea mea, vim ne omittam euripidis, dicat recusabo hendrerit vim te. Mei affert moderatius philosophia te, no pri tale maiorum vivendum.\n\nCu pro consul doming. Et sed meis inermis scaevola. Eos te civibus deterruisset, mea affert essent ex. Sea ea primis quodsi iriure, cu usu wisi meliore luptatum.\n\nEi iudico veniam vix, solet molestiae ex sit. Eum ne vivendum voluptaria, sed ei error timeam disputationi, populo menandri dissentiet ea duo. Vim an illum tritani voluptatibus, ea sed dicunt verterem. Ea fuisset voluptaria dissentias sit.\n\nAnimal perpetua mediocrem ei eam. Nam ex atomorum consulatu, omnes dictas virtute est in. Scripta viderer ut cum, nam scripta fabellas accommodare ea. Per summo habemus conceptam eu, id eros graeco his. Stet erat vis at, cibo accusamus sententiae et qui. Per ne posse scripserit.",
          "job-date":"2016-09-18T00:00:00.000+02:00",
          "hours":6.0,
          "name":"Assembly of Tillfälle cabinet",
          "created-at":"2016-07-16T17:47:10.961+02:00",
          "updated-at":"2016-07-16T17:47:10.961+02:00",
          "zip":"11157",
          "zip-latitude":59.3335278,
          "zip-longitude":18.0656418,
          "verified":false,
          "job-end-date":"2016-09-18T00:00:00.000+02:00",
          "filled":false,
          "short-description":null,
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"403",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/403"
            }
          },
          "company":{
            "data":{
              "id":"31",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/31"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "category":{
            "data":{
              "id":"11245",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/11245"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"8",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/8"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/254"
        }
      },
      {
        "id":"253",
        "type":"jobs",
        "attributes":{
          "description":"I need someone to tell me what a Rangerare is",
          "job-date":"2016-07-22T00:00:00.000+02:00",
          "hours":5.0,
          "name":"Test",
          "created-at":"2016-07-13T21:21:10.299+02:00",
          "updated-at":"2016-07-13T21:21:10.299+02:00",
          "zip":"11122",
          "zip-latitude":59.3351131,
          "zip-longitude":18.0571615,
          "verified":false,
          "job-end-date":"2016-07-27T00:00:00.000+02:00",
          "filled":false,
          "short-description":null,
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"403",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/403"
            }
          },
          "company":{
            "data":{
              "id":"31",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/31"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "category":{
            "data":{
              "id":"11185",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/11185"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"9",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/9"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/253"
        }
      },
      {
        "id":"252",
        "type":"jobs",
        "attributes":{
          "description":"Vi behöver en överpostiljon som kan sitta i vår reception på vardagar kl 8-11 och ta emot inkommande post. Detta testjobb kräver inga förkunskaper.",
          "job-date":"2016-08-12T00:00:00.000+02:00",
          "hours":60.0,
          "name":"Johannas testjobb",
          "created-at":"2016-07-12T14:22:04.227+02:00",
          "updated-at":"2016-07-12T14:22:04.227+02:00",
          "zip":"12266",
          "zip-latitude":59.2690316,
          "zip-longitude":18.0588936,
          "verified":false,
          "job-end-date":"2016-09-10T00:00:00.000+02:00",
          "filled":false,
          "short-description":null,
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"54",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/54"
            }
          },
          "company":{
            "data":{
              "id":"5",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/5"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "category":{
            "data":{
              "id":"12388",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/12388"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"9",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/9"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/252"
        }
      },
      {
        "id":"247",
        "type":"jobs",
        "attributes":{
          "description":"Dog walking in Humlegården.",
          "job-date":"2016-06-22T00:00:00.000+02:00",
          "hours":8.0,
          "name":"Dog walking",
          "created-at":"2016-06-22T09:22:57.760+02:00",
          "updated-at":"2016-07-05T10:38:05.885+02:00",
          "zip":"12231",
          "zip-latitude":59.2839296,
          "zip-longitude":18.0924643,
          "verified":false,
          "job-end-date":"2016-06-22T00:00:00.000+02:00",
          "filled":false,
          "short-description":null,
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"362",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/362"
            }
          },
          "company":{
            "data":{
              "id":"46",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/46"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "category":{
            "data":{
              "id":"12393",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/12393"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"9",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/9"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/247"
        }
      },
      {
        "id":"246",
        "type":"jobs",
        "attributes":{
          "description":"Help out in the reception.",
          "job-date":"2016-06-10T19:00:00.000+02:00",
          "hours":2.0,
          "name":"Receptionist",
          "created-at":"2016-06-21T19:13:49.527+02:00",
          "updated-at":"2016-07-04T10:24:39.348+02:00",
          "zip":"11110",
          "zip-latitude":56.7615387,
          "zip-longitude":9.7996209,
          "verified":false,
          "job-end-date":"2016-06-12T19:00:00.000+02:00",
          "filled":false,
          "short-description":null,
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"184",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/184"
            }
          },
          "company":{
            "data":{
              "id":"31",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/31"
            }
          },
          "language":{
            "data":{
              "id":"155",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/155"
            }
          },
          "category":{
            "data":{
              "id":"12388",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/12388"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"8",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/8"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/246"
        }
      },
      {
        "id":"245",
        "type":"jobs",
        "attributes":{
          "description":"We need a project coordinator for one of our upcoming projects..",
          "job-date":"2016-06-21T00:00:00.000+02:00",
          "hours":8.0,
          "name":"Project coordinator",
          "created-at":"2016-06-21T14:08:28.591+02:00",
          "updated-at":"2016-07-04T10:26:15.142+02:00",
          "zip":"121234",
          "zip-latitude":56.7615387,
          "zip-longitude":9.7996209,
          "verified":false,
          "job-end-date":"2016-06-21T00:00:00.000+02:00",
          "filled":false,
          "short-description":null,
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"399",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/399"
            }
          },
          "company":{
            "data":{
              "id":"61",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/61"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "category":{
            "data":{
              "id":"12393",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/12393"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"7",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/7"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/245"
        }
      },
      {
        "id":"244",
        "type":"jobs",
        "attributes":{
          "description":"Job for test text",
          "job-date":"2016-06-19T19:00:00.000+02:00",
          "hours":2.0,
          "name":"Drummer",
          "created-at":"2016-06-20T16:54:35.078+02:00",
          "updated-at":"2016-07-04T10:20:08.213+02:00",
          "zip":"11110",
          "zip-latitude":56.7615387,
          "zip-longitude":9.7996209,
          "verified":false,
          "job-end-date":"2016-06-19T19:00:00.000+02:00",
          "filled":false,
          "short-description":null,
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"393",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/393"
            }
          },
          "company":{
            "data":{
              "id":"60",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/60"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "category":{
            "data":{
              "id":"12390",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/12390"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"7",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/7"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/244"
        }
      },
      {
        "id":"242",
        "type":"jobs",
        "attributes":{
          "description":"test create job detail",
          "job-date":"2016-06-19T19:00:00.000+02:00",
          "hours":2.0,
          "name":"English teacher",
          "created-at":"2016-06-20T10:55:12.086+02:00",
          "updated-at":"2016-07-04T10:20:35.818+02:00",
          "zip":"11110",
          "zip-latitude":56.7615387,
          "zip-longitude":9.7996209,
          "verified":false,
          "job-end-date":"2016-06-19T19:00:00.000+02:00",
          "filled":false,
          "short-description":null,
          "featured":false
        },
        "relationships":{
          "job-users":{
            "data":[

            ]
          },
          "owner":{
            "data":{
              "id":"393",
              "type":"users"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/393"
            }
          },
          "company":{
            "data":{
              "id":"60",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/60"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "category":{
            "data":{
              "id":"11283",
              "type":"categories"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/categories/11283"
            }
          },
          "hourly-pay":{
            "data":{
              "id":"7",
              "type":"hourly-pays"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/7"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs/242"
        }
      }
    ],
    "included":[
      {
        "id":"403",
        "type":"users",
        "attributes":{
          "first-name":"Per",
          "description":null,
          "job-experience":null,
          "education":null,
          "language-id":37,
          "zip":"",
          "zip-latitude":60.128161,
          "zip-longitude":18.643501,
          "competence-text":null,
          "primary-role":"company"
        },
        "relationships":{
          "company":{
            "data":{
              "id":"31",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/31"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "user-images":{
            "data":[

            ]
          },
          "languages":{
            "data":[
              {
                "id":"37",
                "type":"languages"
              }
            ],
            "links":{
              "related":"https://just-match-api-staging.herokuapp.com/api/v1/users/403/languages"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/403"
        }
      },
      {
        "id":"31",
        "type":"companies",
        "attributes":{
          "name":"test",
          "website":"http://www.test.com",
          "cin":"1234567890",
          "street":"Sveavägen 1",
          "zip":"11850",
          "city":"stockholm",
          "phone":null,
          "email":"4f08b801-214d-437e-b9c6-9410b4efe416@example.com"
        },
        "relationships":{
          "company-images":{
            "data":[

            ]
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/31"
        }
      },
      {
        "id":"9",
        "type":"hourly-pays",
        "attributes":{
          "gross-salary":115,
          "net-salary":80.5,
          "rate-excluding-vat":161.0,
          "rate-including-vat":201.25,
          "active":true,
          "currency":"SEK"
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/9"
        }
      },
      {
        "id":"8",
        "type":"hourly-pays",
        "attributes":{
          "gross-salary":125,
          "net-salary":87.5,
          "rate-excluding-vat":175.0,
          "rate-including-vat":218.75,
          "active":true,
          "currency":"SEK"
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/8"
        }
      },
      {
        "id":"54",
        "type":"users",
        "attributes":{
          "first-name":"Agustin",
          "description":"Flexitarian yolo austin 8-bit chicharrones typewriter selfies. Truffaut narwhal pitchfork.",
          "job-experience":null,
          "education":null,
          "language-id":37,
          "zip":"11850",
          "zip-latitude":59.3164285,
          "zip-longitude":18.0590482,
          "competence-text":null,
          "primary-role":"company"
        },
        "relationships":{
          "company":{
            "data":{
              "id":"5",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/5"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "user-images":{
            "data":[

            ]
          },
          "languages":{
            "data":[

            ],
            "links":{
              "related":"https://just-match-api-staging.herokuapp.com/api/v1/users/54/languages"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/54"
        }
      },
      {
        "id":"5",
        "type":"companies",
        "attributes":{
          "name":"Wisozk, Borer and Bailey",
          "website":null,
          "cin":"7328601815",
          "street":"Sveavägen 1",
          "zip":"11850",
          "city":"stockholm",
          "phone":null,
          "email":"0f074037-b1c8-4f27-aa82-15ad0d398160@example.com"
        },
        "relationships":{
          "company-images":{
            "data":[

            ]
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/5"
        }
      },
      {
        "id":"362",
        "type":"users",
        "attributes":{
          "first-name":"Fredric",
          "description":null,
          "job-experience":null,
          "education":null,
          "language-id":37,
          "zip":"11144",
          "zip-latitude":59.3346662,
          "zip-longitude":18.0693861,
          "competence-text":null,
          "primary-role":"company"
        },
        "relationships":{
          "company":{
            "data":{
              "id":"46",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/46"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "user-images":{
            "data":[
              {
                "id":"177",
                "type":"user-images"
              }
            ]
          },
          "languages":{
            "data":[
              {
                "id":"37",
                "type":"languages"
              }
            ],
            "links":{
              "related":"https://just-match-api-staging.herokuapp.com/api/v1/users/362/languages"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/362"
        }
      },
      {
        "id":"46",
        "type":"companies",
        "attributes":{
          "name":"Universum Global",
          "website":"http://universumglobal.com/",
          "cin":"5562645456",
          "street":"Jakobsbergsgatan 22",
          "zip":"11144",
          "city":"Stockholm",
          "phone":"0735012993",
          "email":"fredric@justarrived.se"
        },
        "relationships":{
          "company-images":{
            "data":[
              {
                "id":"15",
                "type":"company-images"
              }
            ]
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/46"
        }
      },
      {
        "id":"184",
        "type":"users",
        "attributes":{
          "first-name":"Wiratti1 corporate",
          "description":"ABCDEFGHIJKLMNOPQRSTUVWXYZ",
          "job-experience":"job-exp",
          "education":"edu",
          "language-id":155,
          "zip":"11110",
          "zip-latitude":56.7615387,
          "zip-longitude":9.7996209,
          "competence-text":null,
          "primary-role":"company"
        },
        "relationships":{
          "company":{
            "data":{
              "id":"31",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/31"
            }
          },
          "language":{
            "data":{
              "id":"155",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/155"
            }
          },
          "user-images":{
            "data":[
              {
                "id":"77",
                "type":"user-images"
              }
            ]
          },
          "languages":{
            "data":[
              {
                "id":"155",
                "type":"languages"
              }
            ],
            "links":{
              "related":"https://just-match-api-staging.herokuapp.com/api/v1/users/184/languages"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/184"
        }
      },
      {
        "id":"399",
        "type":"users",
        "attributes":{
          "first-name":"Fredri",
          "description":"why is this here?",
          "job-experience":null,
          "education":null,
          "language-id":37,
          "zip":"44453",
          "zip-latitude":58.0498372,
          "zip-longitude":11.8515576,
          "competence-text":null,
          "primary-role":"company"
        },
        "relationships":{
          "company":{
            "data":{
              "id":"61",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/61"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "user-images":{
            "data":[
              {
                "id":"238",
                "type":"user-images"
              }
            ]
          },
          "languages":{
            "data":[
              {
                "id":"37",
                "type":"languages"
              }
            ],
            "links":{
              "related":"https://just-match-api-staging.herokuapp.com/api/v1/users/399/languages"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/399"
        }
      },
      {
        "id":"61",
        "type":"companies",
        "attributes":{
          "name":"hjsuahf",
          "website":"https://www.justarrived.se",
          "cin":"2121211212",
          "street":"123",
          "zip":"44453",
          "city":"sherwoodskogen",
          "phone":"901290",
          "email":"fredric+41@justarrived.se"
        },
        "relationships":{
          "company-images":{
            "data":[

            ]
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/61"
        }
      },
      {
        "id":"7",
        "type":"hourly-pays",
        "attributes":{
          "gross-salary":105,
          "net-salary":73.5,
          "rate-excluding-vat":147.0,
          "rate-including-vat":183.75,
          "active":true,
          "currency":"SEK"
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/hourly-pays/7"
        }
      },
      {
        "id":"393",
        "type":"users",
        "attributes":{
          "first-name":"Wiratti",
          "description":null,
          "job-experience":null,
          "education":null,
          "language-id":37,
          "zip":"11110",
          "zip-latitude":56.7615387,
          "zip-longitude":9.7996209,
          "competence-text":null,
          "primary-role":"company"
        },
        "relationships":{
          "company":{
            "data":{
              "id":"60",
              "type":"companies"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/60"
            }
          },
          "language":{
            "data":{
              "id":"37",
              "type":"languages"
            },
            "links":{
              "self":"https://just-match-api-staging.herokuapp.com/api/v1/languages/37"
            }
          },
          "user-images":{
            "data":[
              {
                "id":"234",
                "type":"user-images"
              }
            ]
          },
          "languages":{
            "data":[
              {
                "id":"37",
                "type":"languages"
              }
            ],
            "links":{
              "related":"https://just-match-api-staging.herokuapp.com/api/v1/users/393/languages"
            }
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/users/393"
        }
      },
      {
        "id":"60",
        "type":"companies",
        "attributes":{
          "name":"testZZZ",
          "website":"http://www.testZZZ.com",
          "cin":"9998887776",
          "street":"Delvorred",
          "zip":"11110",
          "city":"Stockholms",
          "phone":"+4612345678",
          "email":"wirattiZZZ@seproduction.com"
        },
        "relationships":{
          "company-images":{
            "data":[
              {
                "id":"29",
                "type":"company-images"
              }
            ]
          }
        },
        "links":{
          "self":"https://just-match-api-staging.herokuapp.com/api/v1/companies/60"
        }
      }
    ],
    "links":{
      "self":"https://just-match-api-staging.herokuapp.com/api/v1/jobs?filter%5Bfilled%5D=false&include=owner%2Ccompany%2Chourly-pay&page%5Bnumber%5D=1&page%5Bsize%5D=10",
      "next":"https://just-match-api-staging.herokuapp.com/api/v1/jobs?filter%5Bfilled%5D=false&include=owner%2Ccompany%2Chourly-pay&page%5Bnumber%5D=2&page%5Bsize%5D=10",
      "last":"https://just-match-api-staging.herokuapp.com/api/v1/jobs?filter%5Bfilled%5D=false&include=owner%2Ccompany%2Chourly-pay&page%5Bnumber%5D=16&page%5Bsize%5D=10"
    },
    "meta":{
      "total":158
    }
  };

  parse(data: any) {
    let dataActual = data.data;
    // data -> object or array
    let included = data.included;
    let result = {};

    this.setAttributes(dataActual.attributes, result);

    console.log(result);
  }

  private setAttributes(attributes, result) {
    Object.keys(attributes).forEach((key) => {
      result[key] = attributes[key];
    });
  }
}
