/**
 ** Author: Bex
 **
 ** Page component that all page components shall extend.
 **
 ** Handles static meta tags for each page passed via the constructor.
 **
 ** The tags can be updated dynamically via the updatePageMeta method or the
 ** Meta service.
 **
 ** DO NOT EDIT THIS FILE WITHOUT PERMISSION!
 **/

import {BaseComponent} from '../base.component';
import {Meta} from '@angular/platform-browser';
import {OnDestroy} from '@angular/core';
import {OnInit} from '@angular/core';
import {Subscription} from 'rxjs/Subscription';
import {SystemLanguagesResolver} from '../../resolvers/system-languages/system-languages.resolver';
import {TranslateService} from '@ngx-translate/core';
import {UserResolver} from '../../resolvers/user/user.resolver';

export interface PageMeta {
  title: {translate: boolean, content: string},
  description: {translate: boolean, content: string},
  image?: {content: string},
  translateParams?: any
}

export abstract class PageComponent extends BaseComponent implements OnInit, OnDestroy {

  private metaTranslationsSubscription: Subscription;

  public constructor (
    private pageMeta: PageMeta,
    protected document: any,
    protected meta: Meta,
    protected request: any,
    protected systemLanguagesResolver: SystemLanguagesResolver,
    protected translateService: TranslateService,
    protected userResolver: UserResolver,
  ) {
    super(systemLanguagesResolver, userResolver);
  }

  public ngOnInit(): void {
    this.updatePageMeta(this.pageMeta);

    super.ngOnInit();
  }

  protected updatePageMeta(pageMeta: PageMeta) {
    if (this.metaTranslationsSubscription) { this.metaTranslationsSubscription.unsubscribe(); }

    this.pageMeta = pageMeta;

    this.metaTranslationsSubscription = this.translateService.get([this.pageMeta.title.content, this.pageMeta.description.content], this.pageMeta.translateParams)
      .concat(this.translateService.onLangChange.map(event => event.translations))
      .subscribe(translations => {
        for (let language of this.systemLanguagesResolver.getSystemLanguages()) {
          this.meta.removeTag("property='og:locale:alternate'");
        }
        this.meta.removeTag("property='og:image:width'");
        this.meta.removeTag("property='og:image:height'");

        if (this.pageMeta.title.translate) {
          this.meta.updateTag({
            content: translations[this.pageMeta.title.content]
          },
            'property="og:title"'
          );
        } else {
          this.meta.updateTag({
            content: this.pageMeta.title.content
          },
            'property="og:title"'
          );
        }

        if (this.pageMeta.description.translate) {
          this.meta.updateTag({
            content: translations[this.pageMeta.description.content]
          },
            'name="description"'
          );

          this.meta.updateTag({
            content: translations[this.pageMeta.description.content]
          },
            'property="og:description"'
          );
        } else {
          this.meta.updateTag({
            content: this.pageMeta.description.content
          },
            'name="description"'
          );

          this.meta.updateTag({
            content: this.pageMeta.description.content
          },
            'property="og:description"'
          );
        }

        if (this.pageMeta.image) {
          this.meta.updateTag({
            content: this.pageMeta.image.content
          },
            'property="og:image"'
          );
        } else {
          this.meta.updateTag({
            content: this.getBaseUrl() + '/assets/images/open-graph-base.jpg'
          },
            'property="og:image"'
          );
          this.meta.addTag({ property: 'og:image:width', content: '2346' });
          this.meta.addTag({ property: 'og:image:height', content: '1314' });
        }

        this.meta.updateTag({
          content: this.getUrl()
        },
          'property="og:url"'
        );

        this.meta.updateTag({
          content: this.mapToOpenGraphLocale(this.systemLanguagesResolver.getSelectedSystemLanguageCode())
        },
          'property="og:locale"'
        );

        for (let language of this.systemLanguagesResolver.getSystemLanguages()) {
          this.meta.addTag({ property: 'og:locale:alternate', content: this.mapToOpenGraphLocale(language.languageCode) });
        }
      });
  }

  private getUrl(): string {
    // If server side get url from request otherwise document.location.href
    if (this.request) {
      return this.request.protocol + '://' + this.request.headers.host + this.request.url.split("?").shift();
    } else {
      return window.location.origin + window.location.pathname;
    }
  }

  private getBaseUrl(): string {
    // If server side get url from request otherwise document.location.href
    if (this.request) {
      return this.request.protocol + '://' + this.request.headers.host;
    } else {
      return window.location.origin;
    }
  }

  private mapToOpenGraphLocale(languageCode: string): string {
    const openGraphLocaleMap = {
      'ar': 'ar_AR',
      'en': 'en_US',
      'fa_AF': 'fa_IR',
      'fa': 'fa_IR',
      'ku': 'ku_TR',
      'ps': 'ps_AF',
      'sv': 'sv_SE',
      'ti': 'en_US',
    }

    return openGraphLocaleMap[languageCode];
  }

  public ngOnDestroy(): void {
    if (this.metaTranslationsSubscription) { this.metaTranslationsSubscription.unsubscribe(); }
    super.ngOnDestroy();
  }
}
