#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

which npm 2>&1 >/dev/null || {
  echo -e '\nPlease install npm and then run this script again.'
  exit 1
}

which gulp 2>&1 >/dev/null || {
  echo -e '\nNo gulp found installing with $ npm install -g gulp-cli'
  npm install --global gulp-cli
}

script/bootstrap
